### ISSUE TITLE
wayland-eglsurface.c:2562: wlEglDestroySurface: The check assertion "wl_list_empty(&surface->ctx.streamImages)" failed

### ISSUE THREAD

**Issue by dmaliog** [NVIDIA/egl-wayland#127]
I'm creating my application (c++, qt) and it doesn't work on the new egl-wayland version 1.1.15, but it works on version 1.1.13.

dmali@tony-b550gamingxv2 ~ (master) [1]> kLausPro
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/lib/qt6/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/lib/qt6/qtwebengine_dictionaries'
kLausPro: ../egl-wayland/src/wayland-eglsurface.c:2562: wlEglDestroySurface: The check assertion "wl_list_empty(&surface->ctx.streamImages)" failed.
fish: Job 1, 'kLausPro' terminated by signal SIGABRT (Abort)

git: https://github.com/dmaliog/kLausqt

**Comment by amshafer** [comment]
Please provide details, does it fail on startup? Any action that triggers the assertion? Does the `__NV_DISABLE_EXPLICIT_SYNC=1` variable fix the issue?

**Comment by dmaliog** [comment]
The error occurs after splashscreen (while mainwindow.cpp is running), __NV_DISABLE_EXPLICIT_SYNC=1 does not solve the problem

**Comment by amshafer** [comment]
What driver version are you using this with? I didn't see any crashes with your latest release (14.9) from github

**Comment by dmaliog** [comment]
Graphics:
  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] driver: nvidia v: 560.31.02
  Display: wayland server: X.org v: 1.21.1.13 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: X: loaded: nvidia gpu: nvidia
    resolution: 2560x1440
  API: EGL v: 1.5 drivers: nvidia,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: nvidia mesa v: 560.31.02
    renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
  API: Vulkan v: 1.3.285 drivers: nvidia surfaces: xcb,xlib,wayland

OS: EndeavourOS Linux x86_64 
Kernel: 6.10.2-x64v3-xanmod1 
Shell: fish 3.7.1 
DE: Plasma 6.1.4 (Wayland) 
WM: kwin_wayland_wr 
CPU: AMD Ryzen 5 5600 (12) @ 3.500GHz 
GPU: NVIDIA GeForce GTX 1080 Ti

**Comment by amshafer** [comment]
It looks like something in the application is calling eglDestroySurfaceKhr on an already destroyed surface, which then triggers an assert. I'm unable to figure out why as for some reason gdb won't let me step while connected to your application.

**Comment by ptr1337** [comment]
rssguard seems to have an equal issue:
__NV_DISABLE_EXPLICIT_SYNC=1 rssguard

time="     0.000" type="debug" -> core: Starting RSS Guard 4.7.3.
time="     0.000" type="debug" -> core: Current UTC date/time is 2024-08-12T19:47:44Z.
time="     0.104" type="debug" -> core: Initializing settings in '/home/ptr1337/.config/RSS Guard 4/config/config.ini' (non-portable way).
time="     0.104" type="debug" -> core: Starting to load active localization. Desired localization is 'en_US'.


...

 'SELECT Messages.id, Messages.is_read, Messages.is_important, Messages.is_deleted, Messages.is_pdeleted, Messages.feed, Messages.title, Messages.url, Messages.author, Messages.date_created, Messages.contents, Messages.enclosures, Messages.score, Messages.account_id, Messages.custom_id, Messages.custom_hash, Feeds.title, Feeds.is_rtl, CASE WHEN LENGTH(Messages.enclosures) > 10 THEN 'true' ELSE 'false' END AS has_enclosures, (SELECT GROUP_CONCAT(Labels.name) FROM Labels WHERE Messages.labels LIKE "%." || Labels.custom_id || ".%") as msg_labels, Messages.labels FROM Messages LEFT JOIN Feeds ON Messages.feed = Feeds.custom_id AND Messages.account_id = Feeds.account_id WHERE 0 > 1 ORDER BY Messages.date_created DESC;'.
time="     0.254" type="debug" -> core: Showing the main window when the application is starting.
rssguard: ../egl-wayland/src/wayland-eglsurface.c:2562: wlEglDestroySurface: Assertion `wl_list_empty(&surface->ctx.streamImages)' failed.
fish: Job 1, '__NV_DISABLE_EXPLICIT_SYNC=1 rs…' terminated by signal SIGABRT (Abort)

```

**Comment by amshafer** [comment]
Thanks with rssguard I can properly attach gdb and see the issue, will have a fix shortly.

**Comment by VGib** [comment]
Hello same problem with akregator (which yuse a wbe browser plasma widget)
`
vincent@localhost:~> akregator
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/bin/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries'
Path override failed for key base::DIR_APP_DICTIONARIES and path '/usr/libexec/qt6/qtwebengine_dictionaries'
akregator: ../src/wayland-eglsurface.c :2562 : wlEglDestroySurface:  l'assertion « wl_list_empty(&surface->ctx.streamImages) » a échoué.
KCrash: Application 'akregator' crashing... crashRecursionCounter = 2
Abandon (core dumped)
`

using open suse tumbleweed with nvidia 550.100_k5.9.7.1, kernel 6.10.5 and libwayland-egl1 version 1.23.0

Regards,

VGib

**Comment by amshafer** [comment]
Please use egl-wayland version 1.1.16 which contains the fix for this.
