### ISSUE TITLE
EGL/egl.h was required by wayland-eglswap.h but not detected in meson.build/configure.ac

### ISSUE THREAD

**Issue by fundawang** [NVIDIA/egl-wayland#128]
wayland-eglswap.h reads:
```
#include <EGL/egl.h>
#include <EGL/eglext.h>
```

But these two headers are not checked during `meson.build`/`configure.ac`, which means it will produces following errors when compiling:
```
In file included from ../src/wayland-eglswap.c:23:
../include/wayland-eglswap.h:26:10: fatal error: EGL/egl.h: No such file or directory
 #include <EGL/egl.h>
```

**Comment by kbrenneman** [comment]
It looks like we forgot to add an explicit dependency on the EGL headers. Easy enough to add.
