### ISSUE TITLE
Need Info for NixOS : Run installer continue to install 1.1.13

### ISSUE THREAD

**Issue by mrdev023** [NVIDIA/egl-wayland#136]
I'm using NixOS with kde plasma 6.1 but on NixOS, the maintainer use egl-wayland distributed by .run installer so 1.1.13.

egl-wayland 1.1.16 version can be deployed with NVIDIA driver ? On NVIDIA installer (560.35.03) provide egl-wayland 1.1.13 again.

https://github.com/NixOS/nixpkgs/blob/21bc7a6efdcb1d158826547a2609d0a845ebe0cb/pkgs/os-specific/linux/nvidia-x11/builder.sh#L114

But for xwayland, it use separate package egl-wayland, https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/libraries/egl-wayland/default.nix#L59 it's up to date.
It's used only for build package i think, https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/servers/x11/xorg/xwayland.nix#L74

I don't know if /etc/egl/egl_external_platform.d/10_nvidia_wayland.json need to point also to latest version too 

Currently,

egl-wayland package version is 1.1.15 (soon 1.1.16 https://github.com/NixOS/nixpkgs/pull/336667) but seems to be used only for compiling.

```bash
cat /etc/egl/egl_external_platform.d/10_nvidia_wayland.json

# Return 

{
  "file_format_version": "1.0.0",
  "ICD": {
    "library_path": "/nix/store/8hk6bmswzfbk5s6ih7h0sa5ba6bfyp39-nvidia-x11-555.58.02-6.10.1/lib/libnvidia-egl-wayland.so.1"
  }
}

ls -al /nix/store/8hk6bmswzfbk5s6ih7h0sa5ba6bfyp39-nvidia-x11-555.58.02-6.10.1/lib/libnvidia-egl-wayland.so.1

# Return

lrwxrwxrwx 1 root root 31  1 janv.  1970 /nix/store/8hk6bmswzfbk5s6ih7h0sa5ba6bfyp39-nvidia-x11-555.58.02-6.10.1/lib/libnvidia-egl-wayland.so.1 -> libnvidia-egl-wayland.so.1.1.13
```

It look correct for you ?

PS: I know, i use 555 driver not 560 but when i extract .run installer, i see you use egl-wayland 1.1.13 again. 

Or  only rolling release distribution deploy egl-wayland at latest version and ignore configuration from .run installer like here https://gitlab.archlinux.org/archlinux/packaging/packages/egl-wayland/-/blob/main/PKGBUILD?ref_type=heads#L46

I don't know anything about recommandation, i can say mistake.

EDIT: Fedora overwrite also version provided by .run installer https://src.fedoraproject.org/rpms/egl-wayland/blob/f40/f/egl-wayland.spec#_78

**Comment by kbrenneman** [comment]
New versions of egl-wayland are generally backward-compatible with older drivers (modulo any bugs), so you can install 1.1.16 and use that with existing pre-560 drivers.

The reverse is also supposed to be true. That is, older egl-wayland versions should keep working with newer drivers (minus any new features that require newer driver support, obviously). Unfortunately, there was a bug in the version check, so a 560.* driver does need egl-wayland 1.1.14 or 1.1.13.1 to work.

The `libnvidia-egl-wayland.so` build in the .run installer is built from the same sources, but obviously won't have an egl-wayland version newer than what was available when we built that particular driver.

**Comment by mrdev023** [comment]
@kbrenneman But, if i install egl-wayland 1.1.16, /etc/egl/egl_external_platform.d/10_nvidia_wayland.json need to point to egl-wayland 1.1.16 or to egl-wayland provided by run installer ?

Because, nixos always use egl-wayland provided by run installer in /etc/egl/egl_external_platform.d/10_nvidia_wayland.json

**Comment by kbrenneman** [comment]
`10_nvidia_wayland.json` should point to `libnvidia-egl-wayland.so.1`, which in turn should be a symlink to whatever version of egl-wayland you've got installed. The installer, or Meson, or `ldconfig` will update that symlink just like for any other library.

**Comment by mrdev023** [comment]
> `10_nvidia_wayland.json` should point to `libnvidia-egl-wayland.so.1`, which in turn should be a symlink to whatever version of egl-wayland you've got installed. The installer, or Meson, or `ldconfig` will update that symlink just like for any other library.

Okay thx for you reply.
