### ISSUE TITLE
tags missing

### ISSUE THREAD

**Issue by tjaalton** [NVIDIA/egl-wayland#16]
Hi, you don't have tags for 1.0.4, 1.0.5 or 1.1.0. At least the latest should have one.

**Comment by mvicomoya** [comment]
I had them created locally. I guess I never pushed them... Fixed now.

**Comment by fafryd1125** [comment]
REMINDER: 1.1.2 tag is missing.

**Comment by mvicomoya** [comment]
@fafryd1125 Thanks for the heads-up, I just pushed it.
