### ISSUE TITLE
Help with compositor and server

### ISSUE THREAD

**Issue by fsmikedev** [NVIDIA/egl-wayland#21]
Hi,

I've written a wayland server and compositor, I'd like to add EGLStreams support, I'm unsure how to do this using egl-wayland. How does it hook into the wayland server code?

Some guidance would be appreciated.

Thanks.

**Comment by mvicomoya** [comment]
Sorry for the slow response, @fsmikedev.

I think you can look at our `EGLStream` patches for `weston` as an example on how do this:

  https://gitlab.freedesktop.org/mvicomoya/weston

Hope that helps. Feel free to reach out if you run into issues or need further assistance.
