### ISSUE TITLE
Error in ./autogen.sh

### ISSUE THREAD

**Issue by hazzus** [NVIDIA/egl-wayland#22]
Running autogen.sh ends with error on my machine:
```
./configure: line 18106: syntax error near unexpected token `-fvisibility=hidden,'
./configure: line 18106: `AX_CHECK_COMPILE_FLAG(-fvisibility=hidden,'
``` 
Deletion of this command fixes error.  
Any ideas of possible cause? Maybe dependency missing/too old compiler?  
Running on:
`gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) `  
I can provide any specifications if needed, but which?

**Comment by mvicomoya** [comment]
@hazzus, does pull request https://github.com/NVIDIA/egl-wayland/pull/23 help?

**Comment by hazzus** [comment]
@mvicomoya yes, thanks for hotfix
