### ISSUE TITLE
Evolution egl-wayland crash 

### ISSUE THREAD

**Issue by LoJoDo** [NVIDIA/egl-wayland#30]
Using GeForce GTX 1070/PCIe/SSE2 on Intel® Core™ i7 CPU X 990 @ 3.47GHz × 12  and Arch Linux operating system. A full system update is performed each day.

Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   36 bits physical, 48 bits virtual
CPU(s):                          12
On-line CPU(s) list:             0-11
Thread(s) per core:              2
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           44
Model name:                      Intel(R) Core(TM) i7 CPU       X 990  @ 3.47GHz
Stepping:                        2
Frequency boost:                 enabled
CPU MHz:                         1599.102
CPU max MHz:                     3459.0000
CPU min MHz:                     1596.0000
BogoMIPS:                        6930.77
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        12 MiB
NUMA node0 CPU(s):               0-11
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cach
                                 e flushes, SMT vulnerable
Vulnerability Mds:               Vulnerable: Clear CPU buffers attempted, no mic
                                 rocode; SMT vulnerable
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user
                                  pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, STIBP disab
                                 led, RSB filling
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtr
                                 r pge mca cmov pat pse36 clflush dts acpi mmx f
                                 xsr sse sse2 ht tm pbe syscall nx pdpe1gb rdtsc
                                 p lm constant_tsc arch_perfmon pebs bts rep_goo
                                 d nopl xtopology nonstop_tsc cpuid aperfmperf p
                                 ni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 
                                 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt 
                                 aes lahf_lm pti tpr_shadow vnmi flexpriority ep
                                 t vpid dtherm ida arat

Process 1670 (evolution) of user 1000 dumped core.

Stack trace of thread 1670:
#0  0x00007fa94c0c5615 raise (libc.so.6 + 0x3d615)
#1  0x00007fa94c0ae862 abort (libc.so.6 + 0x26862)
#2  0x00007fa94c0ae747 __assert_fail_base.cold (libc.so.6 + 0x26747)
#3  0x00007fa94c0bdbf6 __assert_fail (libc.so.6 + 0x35bf6)
#4  0x00007fa93c7b690c n/a (libnvidia-egl-wayland.so.1 + 0x590c)
#5  0x00007fa93c7b89e1 n/a (libnvidia-egl-wayland.so.1 + 0x79e1)
#6  0x00007fa90057e65f n/a (libEGL_nvidia.so.0 + 0xd365f)
#7  0x00007fa9004fd5ab n/a (libEGL_nvidia.so.0 + 0x525ab)
#8  0x00007fa93c7b69dc n/a (libnvidia-egl-wayland.so.1 + 0x59dc)
#9  0x00007fa900577923 n/a (libEGL_nvidia.so.0 + 0xcc923)
#10 0x00007fa9004f9c55 n/a (libEGL_nvidia.so.0 + 0x4ec55)
#11 0x00007fa94a72fceb wpe_fdo_initialize_for_egl_display (libWPEBackend-fdo-1.0.so.1 + 0x9ceb)
#12 0x00007fa94d120059 n/a (libwebkit2gtk-4.0.so.37 + 0xc19059)
#13 0x00007fa94d124cf8 n/a (libwebkit2gtk-4.0.so.37 + 0xc1dcf8)
#14 0x00007fa94cfa836a n/a (libwebkit2gtk-4.0.so.37 + 0xaa136a)
#15 0x00007fa94cfa9221 n/a (libwebkit2gtk-4.0.so.37 + 0xaa2221)
#16 0x00007fa94cfa9dbd n/a (libwebkit2gtk-4.0.so.37 + 0xaa2dbd)
#17 0x00007fa94cfb07c6 n/a (libwebkit2gtk-4.0.so.37 + 0xaa97c6)
#18 0x00007fa94cfb0cbb n/a (libwebkit2gtk-4.0.so.37 + 0xaa9cbb)
#19 0x00007fa94cfb139d n/a (libwebkit2gtk-4.0.so.37 + 0xaaa39d)
#20 0x00007fa94d05b487 webkit_web_view_run_javascript (libwebkit2gtk-4.0.so.37 + 0xb54487)
#21 0x00007fa94c440872 e_web_view_jsc_run_script (libevolution-util.so + 0x1cd872)
#22 0x00007fa94c440e82 e_web_view_jsc_add_rule_into_style_sheet (libevolution-util.so + 0x1cde82)
#23 0x00007fa94c436e4a n/a (libevolution-util.so + 0x1c3e4a)
#24 0x00007fa94c43d18a e_web_view_update_fonts_settings (libevolution-util.so + 0x1ca18a)
#25 0x00007fa94c43d657 n/a (libevolution-util.so + 0x1ca657)
#26 0x00007fa9441208a7 n/a (libevolution-mail.so + 0x6b8a7)
#27 0x00007fa94fe2726f n/a (libgobject-2.0.so.0 + 0x2126f)
#28 0x00007fa94fe288a4 g_object_new_valist (libgobject-2.0.so.0 + 0x228a4)
#29 0x00007fa94fe28c1a g_object_new (libgobject-2.0.so.0 + 0x22c1a)
#30 0x00007fa944134cda n/a (libevolution-mail.so + 0x7fcda)
#31 0x00007fa94fe270e7 n/a (libgobject-2.0.so.0 + 0x210e7)
#32 0x00007fa94fe288a4 g_object_new_valist (libgobject-2.0.so.0 + 0x228a4)
#33 0x00007fa94fe28c1a g_object_new (libgobject-2.0.so.0 + 0x22c1a)
#34 0x00007fa93e6301d0 n/a (module-mail.so + 0x191d0)
#35 0x00007fa94fe270e7 n/a (libgobject-2.0.so.0 + 0x210e7)
#36 0x00007fa94fe288a4 g_object_new_valist (libgobject-2.0.so.0 + 0x228a4)
#37 0x00007fa94fe28c1a g_object_new (libgobject-2.0.so.0 + 0x22c1a)
#38 0x00007fa950bbb9ea n/a (libevolution-shell.so + 0x229ea)
#39 0x00007fa93e6340d9 n/a (module-mail.so + 0x1d0d9)
#40 0x00007fa94fe270e7 n/a (libgobject-2.0.so.0 + 0x210e7)
#41 0x00007fa94fe288a4 g_object_new_valist (libgobject-2.0.so.0 + 0x228a4)
#42 0x00007fa94fe28c1a g_object_new (libgobject-2.0.so.0 + 0x22c1a)
#43 0x00007fa950bbe31f n/a (libevolution-shell.so + 0x2531f)
#44 0x00007fa950bbdc35 e_shell_window_get_shell_view (libevolution-shell.so + 0x24c35)
#45 0x00007fa950bbec57 e_shell_window_set_active_view (libevolution-shell.so + 0x25c57)
#46 0x00007fa94fe216cf n/a (libgobject-2.0.so.0 + 0x1b6cf)
#47 0x00007fa94fe28dac g_object_setv (libgobject-2.0.so.0 + 0x22dac)
#48 0x00007fa94fe28e7c g_object_set_property (libgobject-2.0.so.0 + 0x22e7c)
#49 0x00007fa94ff46f95 n/a (libgio-2.0.so.0 + 0xe8f95)
#50 0x00007fa94ff4776a g_settings_bind_with_mapping (libgio-2.0.so.0 + 0xe976a)
#51 0x00007fa94ff47d8b g_settings_bind (libgio-2.0.so.0 + 0xe9d8b)
#52 0x00007fa950bc1604 e_shell_window_private_constructed (libevolution-shell.so + 0x28604)
#53 0x00007fa950bbd53f n/a (libevolution-shell.so + 0x2453f)
#54 0x00007fa94fe270e7 n/a (libgobject-2.0.so.0 + 0x210e7)
#55 0x00007fa94fe288a4 g_object_new_valist (libgobject-2.0.so.0 + 0x228a4)
#56 0x00007fa94fe28c1a g_object_new (libgobject-2.0.so.0 + 0x22c1a)
#57 0x00007fa950bbd63b e_shell_window_new (libevolution-shell.so + 0x2463b)
#58 0x00007fa950bacaa9 e_shell_create_shell_window (libevolution-shell.so + 0x13aa9)
#59 0x000055ef8518f960 n/a (evolution + 0x4960)
#60 0x00007fa950937924 g_main_context_dispatch (libglib-2.0.so.0 + 0x52924)
#61 0x00007fa95098b621 n/a (libglib-2.0.so.0 + 0xa6621)
#62 0x00007fa950936e73 g_main_loop_run (libglib-2.0.so.0 + 0x51e73)
#63 0x00007fa95031e4ff gtk_main (libgtk-3.so.0 + 0x1e14ff)

Stack trace of thread 1703:
#0  0x00007fa94c260cf8 pthread_cond_clockwait (libpthread.so.0 + 0xfcf8)
#1  0x00007fa94a307a7e _ZN7bmalloc9Scavenger13threadRunLoopEv (libjavascriptcoregtk-4.0.so.18 + 0x1578a7e)
#2  0x00007fa94a307bea _ZN7bmalloc9Scavenger16threadEntryPointEPS0_ (libjavascriptcoregtk-4.0.so.18 + 0x1578bea)
#3  0x00007fa94a8b2c24 execute_native_thread_routine (libstdc++.so.6 + 0xcfc24)
#4  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#5  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1704:
#0  0x00007fa94c2609c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
#1  0x00007fa94a2f954d _ZN3WTF15ThreadCondition9timedWaitERNS_5MutexENS_8WallTimeE (libjavascriptcoregtk-4.0.so.18 + 0x156a54d)
#2  0x00007fa94a29070d _ZN3WTF10ParkingLot21parkConditionallyImplEPKvRKNS_12ScopedLambdaIFbvEEERKNS3_IFvvEEERKNS_24TimeWithDynamicClockTypeE (libjavascriptcoregtk-4.0.so.18 + 0x150170d)
#3  0x00007fa94a2941dd _ZN3WTF5sleepENS_7SecondsE (libjavascriptcoregtk-4.0.so.18 + 0x15051dd)
#4  0x00007fa94d132a8b n/a (libwebkit2gtk-4.0.so.37 + 0xc2ba8b)
#5  0x00007fa94d1331e9 n/a (libwebkit2gtk-4.0.so.37 + 0xc2c1e9)
#6  0x00007fa94a2950ae _ZN3WTF6Thread10entryPointEPNS0_16NewThreadContextE (libjavascriptcoregtk-4.0.so.18 + 0x15060ae)
#7  0x00007fa94a2f8d1a n/a (libjavascriptcoregtk-4.0.so.18 + 0x1569d1a)
#8  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#9  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1673:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1705:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa95098b5af n/a (libglib-2.0.so.0 + 0xa65af)
#2  0x00007fa950936e73 g_main_loop_run (libglib-2.0.so.0 + 0x51e73)
#3  0x00007fa94a2f6b72 _ZN3WTF7RunLoop3runEv (libjavascriptcoregtk-4.0.so.18 + 0x1567b72)
#4  0x00007fa94a2950ae _ZN3WTF6Thread10entryPointEPNS0_16NewThreadContextE (libjavascriptcoregtk-4.0.so.18 + 0x15060ae)
#5  0x00007fa94a2f8d1a n/a (libjavascriptcoregtk-4.0.so.18 + 0x1569d1a)
#6  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#7  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1672:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa95098b5af n/a (libglib-2.0.so.0 + 0xa65af)
#2  0x00007fa950936131 g_main_context_iteration (libglib-2.0.so.0 + 0x51131)
#3  0x00007fa950936182 n/a (libglib-2.0.so.0 + 0x51182)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1680:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa94feeedae g_socket_condition_timed_wait (libgio-2.0.so.0 + 0x90dae)
#2  0x00007fa94feef119 n/a (libgio-2.0.so.0 + 0x91119)
#3  0x00007fa94fecfc81 g_input_stream_read (libgio-2.0.so.0 + 0x71c81)
#4  0x00007fa93c88aef5 n/a (libgiognutls.so + 0xdef5)
#5  0x00007fa93c570487 n/a (libgnutls.so.30 + 0x3e487)
#6  0x00007fa93c56659f n/a (libgnutls.so.30 + 0x3459f)
#7  0x00007fa93c568cc4 n/a (libgnutls.so.30 + 0x36cc4)
#8  0x00007fa93c88ba81 n/a (libgiognutls.so + 0xea81)
#9  0x00007fa93c89029e n/a (libgiognutls.so + 0x1329e)
#10 0x00007fa93c890465 n/a (libgiognutls.so + 0x13465)
#11 0x00007fa94fecfc81 g_input_stream_read (libgio-2.0.so.0 + 0x71c81)
#12 0x00007fa950ae1679 n/a (libcamel-1.2.so.62 + 0xc9679)
#13 0x00007fa950ae19ca camel_stream_read (libcamel-1.2.so.62 + 0xc99ca)
#14 0x00007fa93dad6515 n/a (libcamelpop3.so + 0xa515)
#15 0x00007fa93dad6a0a camel_pop3_stream_line (libcamelpop3.so + 0xaa0a)
#16 0x00007fa93dad178a camel_pop3_engine_iterate (libcamelpop3.so + 0x578a)
#17 0x00007fa93dad2857 n/a (libcamelpop3.so + 0x6857)
#18 0x00007fa950a7a23e camel_folder_refresh_info_sync (libcamel-1.2.so.62 + 0x6223e)
#19 0x00007fa93dad43af camel_pop3_folder_new (libcamelpop3.so + 0x83af)
#20 0x00007fa950ad7aa8 n/a (libcamel-1.2.so.62 + 0xbfaa8)
#21 0x00007fa950adbd65 camel_store_get_inbox_folder_sync (libcamel-1.2.so.62 + 0xc3d65)
#22 0x00007fa93e7c5e01 e_mail_session_get_inbox_sync (libemail-engine.so + 0x1be01)
#23 0x00007fa93e7d3879 n/a (libemail-engine.so + 0x29879)
#24 0x00007fa93e7d238d n/a (libemail-engine.so + 0x2838d)
#25 0x00007fa950967bd7 n/a (libglib-2.0.so.0 + 0x82bd7)
#26 0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#27 0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#28 0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1702:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1676:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa95098b5af n/a (libglib-2.0.so.0 + 0xa65af)
#2  0x00007fa950936e73 g_main_loop_run (libglib-2.0.so.0 + 0x51e73)
#3  0x00007fa95007e793 n/a (libedataserver-1.2.so.25 + 0x62793)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1694:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1681:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1687:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1696:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa9509079a4 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x229a4)
#4  0x00007fa950967c7a n/a (libglib-2.0.so.0 + 0x82c7a)
#5  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#6  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#7  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1686:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa94feeedae g_socket_condition_timed_wait (libgio-2.0.so.0 + 0x90dae)
#2  0x00007fa94feef119 n/a (libgio-2.0.so.0 + 0x91119)
#3  0x00007fa94fecfc81 g_input_stream_read (libgio-2.0.so.0 + 0x71c81)
#4  0x00007fa93c88aef5 n/a (libgiognutls.so + 0xdef5)
#5  0x00007fa93c570487 n/a (libgnutls.so.30 + 0x3e487)
#6  0x00007fa93c56659f n/a (libgnutls.so.30 + 0x3459f)
#7  0x00007fa93c568cc4 n/a (libgnutls.so.30 + 0x36cc4)
#8  0x00007fa93c88ba81 n/a (libgiognutls.so + 0xea81)
#9  0x00007fa93c89029e n/a (libgiognutls.so + 0x1329e)
#10 0x00007fa93c890465 n/a (libgiognutls.so + 0x13465)
#11 0x00007fa94fecfc81 g_input_stream_read (libgio-2.0.so.0 + 0x71c81)
#12 0x00007fa950ae1679 n/a (libcamel-1.2.so.62 + 0xc9679)
#13 0x00007fa950ae19ca camel_stream_read (libcamel-1.2.so.62 + 0xc99ca)
#14 0x00007fa93dad6515 n/a (libcamelpop3.so + 0xa515)
#15 0x00007fa93dad6a0a camel_pop3_stream_line (libcamelpop3.so + 0xaa0a)
#16 0x00007fa93dad178a camel_pop3_engine_iterate (libcamelpop3.so + 0x578a)
#17 0x00007fa93dad2857 n/a (libcamelpop3.so + 0x6857)
#18 0x00007fa950a7a23e camel_folder_refresh_info_sync (libcamel-1.2.so.62 + 0x6223e)
#19 0x00007fa93dad43af camel_pop3_folder_new (libcamelpop3.so + 0x83af)
#20 0x00007fa950ad7aa8 n/a (libcamel-1.2.so.62 + 0xbfaa8)
#21 0x00007fa950adbd65 camel_store_get_inbox_folder_sync (libcamel-1.2.so.62 + 0xc3d65)
#22 0x00007fa93e7c5e01 e_mail_session_get_inbox_sync (libemail-engine.so + 0x1be01)
#23 0x00007fa93e7d3879 n/a (libemail-engine.so + 0x29879)
#24 0x00007fa93e7d238d n/a (libemail-engine.so + 0x2838d)
#25 0x00007fa950967bd7 n/a (libglib-2.0.so.0 + 0x82bd7)
#26 0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#27 0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#28 0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1677:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1674:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa95098b5af n/a (libglib-2.0.so.0 + 0xa65af)
#2  0x00007fa950936e73 g_main_loop_run (libglib-2.0.so.0 + 0x51e73)
#3  0x00007fa94ff5ffe8 n/a (libgio-2.0.so.0 + 0x101fe8)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1689:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1691:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1688:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1675:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa95098b5af n/a (libglib-2.0.so.0 + 0xa65af)
#2  0x00007fa950936131 g_main_context_iteration (libglib-2.0.so.0 + 0x51131)
#3  0x00007fa950b8ec0e n/a (libdconfsettings.so + 0x5c0e)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1706:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa95098b5af n/a (libglib-2.0.so.0 + 0xa65af)
#2  0x00007fa950936e73 g_main_loop_run (libglib-2.0.so.0 + 0x51e73)
#3  0x00007fa94a2f6b72 _ZN3WTF7RunLoop3runEv (libjavascriptcoregtk-4.0.so.18 + 0x1567b72)
#4  0x00007fa94a2950ae _ZN3WTF6Thread10entryPointEPNS0_16NewThreadContextE (libjavascriptcoregtk-4.0.so.18 + 0x15060ae)
#5  0x00007fa94a2f8d1a n/a (libjavascriptcoregtk-4.0.so.18 + 0x1569d1a)
#6  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#7  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1693:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1695:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1697:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1692:
#0  0x00007fa94c17d46f __poll (libc.so.6 + 0xf546f)
#1  0x00007fa94feeedae g_socket_condition_timed_wait (libgio-2.0.so.0 + 0x90dae)
#2  0x00007fa94feef119 n/a (libgio-2.0.so.0 + 0x91119)
#3  0x00007fa94fecfc81 g_input_stream_read (libgio-2.0.so.0 + 0x71c81)
#4  0x00007fa93c88aef5 n/a (libgiognutls.so + 0xdef5)
#5  0x00007fa93c570487 n/a (libgnutls.so.30 + 0x3e487)
#6  0x00007fa93c56659f n/a (libgnutls.so.30 + 0x3459f)
#7  0x00007fa93c568cc4 n/a (libgnutls.so.30 + 0x36cc4)
#8  0x00007fa93c88ba81 n/a (libgiognutls.so + 0xea81)
#9  0x00007fa93c89029e n/a (libgiognutls.so + 0x1329e)
#10 0x00007fa93c890465 n/a (libgiognutls.so + 0x13465)
#11 0x00007fa94fecfc81 g_input_stream_read (libgio-2.0.so.0 + 0x71c81)
#12 0x00007fa950ae1679 n/a (libcamel-1.2.so.62 + 0xc9679)
#13 0x00007fa950ae19ca camel_stream_read (libcamel-1.2.so.62 + 0xc99ca)
#14 0x00007fa93dad6515 n/a (libcamelpop3.so + 0xa515)
#15 0x00007fa93dad6a0a camel_pop3_stream_line (libcamelpop3.so + 0xaa0a)
#16 0x00007fa93dad178a camel_pop3_engine_iterate (libcamelpop3.so + 0x578a)
#17 0x00007fa93dad2857 n/a (libcamelpop3.so + 0x6857)
#18 0x00007fa950a7a23e camel_folder_refresh_info_sync (libcamel-1.2.so.62 + 0x6223e)
#19 0x00007fa93dad43af camel_pop3_folder_new (libcamelpop3.so + 0x83af)
#20 0x00007fa950ad7aa8 n/a (libcamel-1.2.so.62 + 0xbfaa8)
#21 0x00007fa950adbd65 camel_store_get_inbox_folder_sync (libcamel-1.2.so.62 + 0xc3d65)
#22 0x00007fa93e7c5e01 e_mail_session_get_inbox_sync (libemail-engine.so + 0x1be01)
#23 0x00007fa93e7d3879 n/a (libemail-engine.so + 0x29879)
#24 0x00007fa93e7d238d n/a (libemail-engine.so + 0x2838d)
#25 0x00007fa950967bd7 n/a (libglib-2.0.so.0 + 0x82bd7)
#26 0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#27 0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#28 0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

Stack trace of thread 1698:
#0  0x00007fa94c182d5d syscall (libc.so.6 + 0xfad5d)
#1  0x00007fa950985b2b g_cond_wait_until (libglib-2.0.so.0 + 0xa0b2b)
#2  0x00007fa950907813 n/a (libglib-2.0.so.0 + 0x22813)
#3  0x00007fa950967d2b n/a (libglib-2.0.so.0 + 0x82d2b)
#4  0x00007fa950964d21 n/a (libglib-2.0.so.0 + 0x7fd21)
#5  0x00007fa94c25a3e9 start_thread (libpthread.so.0 + 0x93e9)
#6  0x00007fa94c188293 __clone (libc.so.6 + 0x100293)

**Comment by erik-kz** [comment]
This should be fixed by commits 9558ec02d0f7bbf30dc1f9ee4c0b06c9b0c49afe and 9c9c4c684983f7b0821f516f8821118170a785ea which will be part of the next release.
