### ISSUE TITLE
Incompatibility with rust wayland-client crate

### ISSUE THREAD

**Issue by wez** [NVIDIA/egl-wayland#34]
When trying to run [wezterm](https://github.com/wez/wezterm) under Wayland, EGL initialization fails with BAD_NATIVE_WINDOW.

Getting this under a debugger, it looks like this runtime check is the critical piece:

```
#1  wlEglIsWaylandWindowValid (window=window@entry=0x55555a44f740) at ../src/wayland-eglsurface.c:74
74          return WL_CHECK_INTERFACE_TYPE(surface, wl_surface_interface);
```

Poking around at the surface that was passed in:

```
>>> p surface
$5 = (struct wl_surface *) 0x555559938800
>>> p *(void**)surface
$8 = (void *) 0x555559904ea8 <wayland_client::protocol::wl_surface::wl_surface_interface>
>>> p *(struct wl_interface*)0x555559904ea8
$12 = {
  name = 0x555558d3994c "wl_surface",
  version = 4,
  method_count = 10,
  methods = 0x555559904d78 <wayland_client::protocol::wl_surface::wl_surface_requests>,
  event_count = 2,
  events = 0x555559904e78 <wayland_client::protocol::wl_surface::wl_surface_events>
}
```

And comparing with the `wl_surface` type that is checked against by this part of the macro:

https://github.com/NVIDIA/egl-wayland/blob/9c9c4c684983f7b0821f516f8821118170a785ea/include/wayland-eglutils.h#L60

```
>>> p &wl_surface_interface
$13 = (const struct wl_interface *) 0x7ffff7d4aa00 <wl_surface_interface>
>>> p wl_surface_interface
$14 = {
  name = 0x7ffff7d46a88 "wl_surface",
  version = 4,
  method_count = 10,
  methods = 0x7ffff7d4a540 <wl_surface_requests>,
  event_count = 2,
  events = 0x7ffff7d4a500 <wl_surface_events>
}
```

The interface appears to be compatible if the check were to perform a comparison of what's inside the `wl_interface`, even though the addresses are not identical.

Why aren't the addresses identical?

The rust client implementation employs code generation to produce most of its code; here's an example of the definition of that particular interface:

https://docs.rs/wayland-client/0.28.1/src/wayland_client/opt/rustwide/target/debug/build/wayland-client-fdd09ed62affdce6/out/wayland_api.rs.html#5885-5892

The rust client does, however, call out to the system libraries so that it should be comptible with EGL libraries.
This same code runs fine when run against the nouveau driver.

So!  Should NVIDIA/egl-wayland project be performing a deeper wl_interface comparison here to unblock this usage?

**Comment by wez** [comment]
this comment https://github.com/Smithay/wayland-rs/issues/374#issuecomment-778716363 suggests expanding the pointer check in the same way that libwayland's `wl_interface_equal` function works.

**Comment by erik-kz** [comment]
Thanks for the detailed report. I agree we should fall back to checking the interface name if the pointer check fails. The only tricky thing is that we try to be safe about dereferencing the pointer (currently by calling mincore), however we should be able to work something out.

**Comment by niklaskorz** [comment]
> Thanks for the detailed report. I agree we should fall back to checking the interface name if the pointer check fails. The only tricky thing is that we try to be safe about dereferencing the pointer (currently by calling mincore), however we should be able to work something out.

As this is blocking all other Rust-based OpenGL applications I know (e.g., Alacritty or glutin-based applications in general), is there any progress on this @erik-kz ?

**Comment by erik-kz** [comment]
A fix is under internal code-review at NVIDIA, should be able to get pushed within the next few days. Apologies for the delay.

**Comment by erik-kz** [comment]
Should be fixed by https://github.com/NVIDIA/egl-wayland/commit/2eb4628d64a8297fb4c08aa796fdf33ff54a670f Again, sorry sorry sorry this took so damned long. Note that there are a few more changes to this library coming in the next few days, so I'm going to wait to those to land, but will bump the release as soon as they do.

**Comment by colemickens** [comment]
Has this shipped in the egl-wayland used in NVIDIA releases now?

**Comment by benwah** [comment]
Heads-up.

If you're using nvidia drivers on Debian, you may encounter:

```
$ cargo run --features wayland --example bloom_2d
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/examples/bloom_2d`
2024-02-19T14:20:41.850376Z  INFO bevy_winit::system: Creating new window "App" (0v1)
2024-02-19T14:20:41.938182Z ERROR log: get_physical_device_surface_support: Initialization of an object has failed    
2024-02-19T14:20:41.958387Z  INFO bevy_render::renderer: AdapterInfo { name: "llvmpipe (LLVM 17.0.6, 256 bits)", vendor: 65541, device: 0, device_type: Cpu, driver: "llvmpipe", driver_info: "Mesa 23.3.5-1 (LLVM 17.0.6)", backend: Vulkan }
2024-02-19T14:20:42.397782Z  INFO bevy_diagnostic::system_information_diagnostics_plugin::internal: SystemInfo { os: "Linux  Debian GNU/Linux", kernel: "6.6.15-amd64", cpu: "AMD Ryzen 9 5900X 12-Core Processor", core_count: "12", memory: "62.7 GiB" }
2024-02-19T14:20:45.618080Z  INFO bevy_window::system: No windows are open, exiting
2024-02-19T14:20:45.620763Z  INFO bevy_winit::system: Closing window 0v1
```

This happened when I tried executing https://github.com/bevyengine/bevy examples.

This was also solved by the "symlink" solution above: https://github.com/NVIDIA/egl-wayland/issues/34#issuecomment-953176437

More specifically I ran:

```
sudo ln -s /usr/lib/x86_64-linux-gnu/nvidia/current/libnvidia-vulkan-producer.so.525.147.05 /usr/lib/libnvidia-vulkan-producer.so
```
