### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [NVIDIA/egl-wayland#46]
:thought_balloon: [Two null pointer checks are not needed](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") before the calls “`free(protocols.drm_name)`” in [the function “wlEglGetPlatformDisplayExport”](https://github.com/NVIDIA/egl-wayland/blob/d4937adc5cd04ac7df98fc5616e40319fb52fdee/src/wayland-egldisplay.c#L653 "Update candidate").

**Comment by erik-kz** [comment]
While these NULL checks may be unnecessary, they aren't doing any harm.
