### ISSUE TITLE
Crashes when windows are resized on HEAD

### ISSUE THREAD

**Issue by kkartaltepe** [NVIDIA/egl-wayland#59]
resizing windows on the latest commit bf86b94d1855ab96ccc9bd0169f179c869d25adf appears to cause many applications to crash. Including obs-studio, firefox, and this trivial [wayland example](https://github.com/kkartaltepe/wayland-egl-simple)

Release 1.1.10 does not appear to have this regression

-- edit
Testing was done on wlroots/sway (c20468cfa, a55472c6 respectively)

**Comment by erik-kz** [comment]
Thanks for catching this, https://github.com/NVIDIA/egl-wayland/commit/bf86b94d1855ab96ccc9bd0169f179c869d25adf does seem to be the regression point. The reason for that change was to properly handle potential failures of eglCreateStreamProducerSurface, but I think it's wrong to always terminate the buffer release thread in destroy_surface_context.

**Comment by kkartaltepe** [comment]
This appears resolved on the latest commits to HEAD.
