### ISSUE TITLE
Plasma wayland - black screen in Ver 1.1.9-1 

### ISSUE THREAD

**Issue by parithy** [NVIDIA/egl-wayland#61]
Plasma shell fails to launch and in the logs below errors are seen
[destroyed object]: error 7: importing the supplied dmabufs failed
The Wayland connection broke. Did the Wayland compositor die?

similar errors are seen even in systemsettings of KDE

but works if launched with 
 env QT_QPA_PLATFORM=xcb systemsettings

works fine on intel

**Comment by erik-kz** [comment]
Could you check what version of Mesa you have installed? As mentioned here http://us.download.nvidia.com/XFree86/Linux-x86_64/515.48.07/README/gbm.html using a GBM-based compositor (such as Kwin) requires at least 21.2.

**Comment by parithy** [comment]
dpkg -l | grep -i mesa
ii  libegl-mesa0:amd64                            22.1.3-1ubuntu1                             amd64        free implementation of the EGL API -- Mesa vendor library
ii  libegl1-mesa-dev:amd64                        22.1.3-1ubuntu1                             amd64        free implementation of the EGL API -- development files
ii  libgl1-mesa-dri:amd64                         22.1.3-1ubuntu1                             amd64        free implementation of the OpenGL API -- DRI modules
ii  libgl1-mesa-dri:i386                          22.1.3-1ubuntu1                             i386         free implementation of the OpenGL API -- DRI modules
ii  libglapi-mesa:amd64                           22.1.3-1ubuntu1                             amd64        free implementation of the GL API -- shared library
ii  libglapi-mesa:i386                            22.1.3-1ubuntu1                             i386         free implementation of the GL API -- shared library
ii  libglu1-mesa:amd64                            9.0.2-1                                     amd64        Mesa OpenGL utility library (GLU)
ii  libglu1-mesa-dev:amd64                        9.0.2-1                                     amd64        Mesa OpenGL utility library -- development files
ii  libglx-mesa0:amd64                            22.1.3-1ubuntu1                             amd64        free implementation of the OpenGL API -- GLX vendor library
ii  libglx-mesa0:i386                             22.1.3-1ubuntu1                             i386         free implementation of the OpenGL API -- GLX vendor library
ii  libwayland-egl1-mesa:amd64                    22.1.3-1ubuntu1                             amd64        transitional dummy package
ii  mesa-common-dev:amd64                         22.1.3-1ubuntu1                             amd64        Developer documentation for Mesa
ii  mesa-utils                                    8.5.0-1                                     amd64        Miscellaneous Mesa utilities -- symlinks
ii  mesa-utils-bin:amd64                          8.5.0-1                                     amd64        Miscellaneous Mesa utilities -- native applications
ii  mesa-va-drivers:amd64                         22.1.3-1ubuntu1                             amd64        Mesa VA-API video acceleration drivers
ii  mesa-vdpau-drivers:amd64                      22.1.3-1ubuntu1                             amd64        Mesa VDPAU video acceleration drivers
ii  mesa-vulkan-drivers:amd64                     22.1.3-1ubuntu1                             amd64        Mesa Vulkan graphics drivers
ii  mesa-vulkan-drivers:i386                      22.1.3-1ubuntu1                             i386         Mesa Vulkan graphics drivers

**Comment by erik-kz** [comment]
Thanks, another thing to confirm is that DRM-KMS is enabled for the nvidia-drm module. Does `cat /sys/module/nvidia_drm/parameters/modeset` print "Y"?

**Comment by parithy** [comment]
yes. it does print Y.

when launching apps with env __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA __GLX_VENDOR_LIBRARY_NAME=nvidia apps like steam, glxgears, are working well

**Comment by erik-kz** [comment]
Is this a PRIME / hybrid-graphics system? Also, do you have a display attached to the NVIDIA GPU?

**Comment by carlosdem** [comment]
Hi.  Sorry to hijack this thread.  I also meet all of the conditions listed above.  Mesa 22.3git, kernel 5.19.1, nvidia driver 515.65, Kwin_wayland 5.96.0+p20.04+tunstable+git20220811.0137-0, qtwayland patched from KDE git

My nvidia gpu is the discrete gpu on my laptop. Te external monitor is usb-c which is controlled by the GP107M [GeForce GTX 1050 Ti Mobile].

All qml apps fail to run once kernel modules are loaded with the error "[destroyed object]: error 7: importing the supplied dmabufs failed"

Any advice?

**Comment by carlosdem** [comment]
scratch that.  Upgrading egl-wayland to git master has done the job.  Everything works well again.

**Comment by lazystone** [comment]
Had the same problem - updating to 1.1.10 helped.
