### ISSUE TITLE
Tag release 1.11

### ISSUE THREAD

**Issue by sviande** [NVIDIA/egl-wayland#66]
Hi,

The tag [1.1.11](https://github.com/NVIDIA/egl-wayland/releases/tag/1.1.11)  doesn't target the latest commit 1bac426 `bump version to 1.1.11`
instead the tag points to b250906

Can you move the tag to 1bac426 ?

Thanks

**Comment by erik-kz** [comment]
Thanks, corrected.

**Comment by sviande** [comment]
thanks
