### ISSUE TITLE
`env->egl_display = eglGetDisplay((EGLNativeDisplayType)wl_display)` return NULL

### ISSUE THREAD

**Issue by xeechou** [NVIDIA/egl-wayland#9]
Hi,

I am having a problem using the EGL implementation, I am running on Ubuntu 16.04 and using nvidia-387 driver. I am having trouble using the EGL wayland platform on my machine.

I installed the library under `/usr/local` and created `/usr/share/egl_external_platform.d/10_nvidia.json`. and the EGL library came with the system. 

I couldn't get a valid EGLDisplay handle using either `eglGetDisplay` or `eglGetPlatformDisplay`. I hope to know if there is anything missing with the system setup to get the program to run? Also the result of `eglQueryString(EGL_NO_DISPLAY', EGL_EXTENSIONS)` gave me: `EGL_EXT_platform_base EGL_EXT_device_base EGL_KHR_debug EGL_EXT_platform_x11 EGL_EXT_platform_device`. Is this because of the system driver problem?

Thank you very much.

**Comment by xeechou** [comment]
As I digging into the code, I found that I need to use `loadexternalplatform` to load the `egl_ext_platform_wayland`. But that function requires an initialized `EGLEXTDriver` that I don't know how to initialize it. How do I initialize `EGLEXTDriver`.

Thx very much.

**Comment by mvicomoya** [comment]
I don't know what's wrong with my email notifications for this repo, but I totally missed this.

I think https://github.com/NVIDIA/egl-wayland/issues/9#issuecomment-371188948 was also asked and resolved in the devtalk forums: https://devtalk.nvidia.com/default/topic/1025647/linux/unable-to-load-my-own-egl-external-library-/post/5245149/#5245149

However, as I understand https://github.com/NVIDIA/egl-wayland/issues/9#issue-302886590 , you're trying to make a client application work with wayland and the NVIDIA driver, `loadEGLExternalPlatform` has nothing to do with it.

First, you need to make sure `libnvidia-egl-wayland.so` is in your system and can be found by [`dlopen(3)`](https://linux.die.net/man/3/dlopen). If you use the NVIDIA installer, you'd have it already in your system (most likely under `/usr/lib`).

Second, you need the json file. You seem to have added it already.

One you have both the library and json files in your system, you should get `EGL_EXT_platform_wayland` in the EGL client extensions string too. If that isn't the case, you're probably missing something.

Can you [`strace(1)`](https://linux.die.net/man/1/strace) your application to see whether the json file and/or the library are being loaded at all?

**Comment by mvicomoya** [comment]
Also, note that our driver will try to [`dlopen(3)`](https://linux.die.net/man/3/dlopen) the library using the filename as stated in the json file. That may or may not match with the actual library's filename and/or SONAME.

[`ldconfig(8)`](https://linux.die.net/man/8/ldconfig) should always be run after installing a library to any of the default locations, or otherwise create all the appropriate symlinks that may be needed.

This is the output I get on my system:
```
[~]$ ls -l /usr/lib/libnvidia-egl-wayland.*
lrwxrwxrwx 1 root root     30 Mar 15 18:06 /usr/lib/libnvidia-egl-wayland.so.1 -> libnvidia-egl-wayland.so.1.0.3
-rwxr-xr-x 1 root root 145814 Mar 15 18:06 /usr/lib/libnvidia-egl-wayland.so.1.0.3
```

**Comment by mvicomoya** [comment]
I haven't heard anything else related to this. Closing.
